/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "alwaysontop.c"
#include "aspectresize.c"
#include "attachx.c"
#include "recttoclient.c"
#include "banish.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "shift.c"
#include "shifttag.c"
#include "shiftview.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xresources.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"

