/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"

/* Other patches */
#include "alwaysontop.h"
#include "aspectresize.h"
#include "attachx.h"
#include "recttoclient.h"
#include "banish.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shifttag.h"
#include "shiftview.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
#include "xresources.h"
/* Layouts */
#include "layout_monocle.h"
#include "layout_tile.h"

